Updated php-etl contract versions
php-etl/zoho-crm-flow pull request #11
Opened 2023-11-20 14:06 UTC by sebprt

2023-11-22 10:54 UTC, JoMessina reviewed
phpstan 4 est cassé ici, c'est prévu d'être corrigé via d'autres packages ?

2023-11-23 14:25 UTC, JoMessina reviewed
Remarque concernant les workflow github. Sur l'action phpstan 5 dans quality tu set un php_version qui n'est pas fait ailleurs. Est-ce obligatoire ou pas ? Il faut peut-être normaliser ici.

2023-11-23 15:08 UTC, JoMessina approved these changes

2023-11-24 09:33 UTC, JoMessina approved these changes

2023-11-24 10:36 UTC, gplanchat requested changes

2023-11-24 10:36 UTC, gplanchat commented on src/Client/Client.php
> -     */
Pourquoi ces docs son supprimées ?

2023-11-24 10:36 UTC, gplanchat commented on src/ContactLoader.php
> +                    $exception->getMessage(),
Le message de l'exception contient probablement une formulation très technique que tu vas envoyer directement à ton client, dans l'interface.

Envoies un message utile au client, qui lui permette de comprendre et/ou résoudre le problème.

2023-11-24 10:36 UTC, gplanchat commented on src/ContactLoader.php
> +                    $exception->getMessage(),
idem

2023-11-24 10:36 UTC, gplanchat commented on src/ContactLoader.php
> +                    $exception->getMessage(),
idem

2023-11-24 10:36 UTC, gplanchat commented on src/ContactLookup.php
> +                    $exception->getMessage(),
idem

2023-11-29 15:27 UTC, sebprt commented on src/Client/Client.php
> -     */
Elles ont été supprimé car elle posait des problème au niveau de PHPStan

2023-11-29 15:38 UTC, sebprt commented on src/ContactLoader.php
> +                    $exception->getMessage(),
Modifié

2023-11-29 15:38 UTC, sebprt commented on src/ContactLoader.php
> +                    $exception->getMessage(),
Modifié

2023-11-29 15:38 UTC, sebprt commented on src/ContactLookup.php
> +                    $exception->getMessage(),
Modifié

2023-11-29 15:38 UTC, sebprt commented on src/ContactLoader.php
> +                    $exception->getMessage(),
Modifié

2023-11-29 16:13 UTC, sebprt commented on src/Client/Client.php
> -     */
![image](https://github.com/php-etl/zoho-crm-flow/assets/47692802/70bbc6b2-fde3-4f72-b8d8-68a50c02ab9a)

2023-11-29 16:17 UTC, sebprt commented on src/Client/Client.php
> -     */
J'ai modifié mon annotation plutôt comme ceci

![image](https://github.com/php-etl/zoho-crm-flow/assets/47692802/bb3ffe54-c289-4493-9d92-86905351be6d)

2023-12-19 20:32 UTC, gplanchat requested changes

2023-12-19 20:32 UTC, gplanchat commented on src/Client/Client.php
> +     * @throws BadRequestException|ForbiddenException|NotFoundException|RequestEntityTooLargeException|ApiRateExceededException|InternalServerErrorException|MultiStatusResponseException
```suggestion
     * @throws BadRequestException
     * @throws ForbiddenException
     * @throws NotFoundException
     * @throws RequestEntityTooLargeException
     * @throws ApiRateExceededException
     * @throws InternalServerErrorException
     * @throws MultiStatusResponseException
```

2023-12-19 20:32 UTC, gplanchat commented on src/Client/Client.php
> +     * @throws BadRequestException|ForbiddenException|NotFoundException|RequestEntityTooLargeException|ApiRateExceededException|InternalServerErrorException|MultiStatusResponseException
```suggestion
     * @throws BadRequestException
     * @throws ForbiddenException
     * @throws NotFoundException
     * @throws RequestEntityTooLargeException
     * @throws ApiRateExceededException
     * @throws InternalServerErrorException
     * @throws MultiStatusResponseException
```

2023-12-19 20:32 UTC, gplanchat commented on src/Client/Client.php
> +     * @throws BadRequestException|ForbiddenException|NotFoundException|RequestEntityTooLargeException|ApiRateExceededException|InternalServerErrorException|MultiStatusResponseException
```suggestion
     * @throws BadRequestException
     * @throws ForbiddenException
     * @throws NotFoundException
     * @throws RequestEntityTooLargeException
     * @throws ApiRateExceededException
     * @throws InternalServerErrorException
     * @throws MultiStatusResponseException
```

2023-12-20 08:19 UTC, sebprt commented on src/Client/Client.php
> +     * @throws BadRequestException|ForbiddenException|NotFoundException|RequestEntityTooLargeException|ApiRateExceededException|InternalServerErrorException|MultiStatusResponseException
Suggestion appliquée

2024-01-10 13:34 UTC, gplanchat approved these changes

2024-01-10 16:30 UTC, gplanchat approved these changes

2024-01-11 08:09 UTC, JoMessina approved these changes

2024-01-11 11:23 UTC, merged