handle the case when zoho responds with multiple statuses for a batch
php-etl/zoho-crm-flow pull request #9
Opened 2023-10-06 15:32 UTC by clemzarch

contrainte : Zoho renvoie chaque status de chaque item sans id ni clé, donc pour savoir quel item a échoué il faut regarder la position du status dans la réponse, et regarder l'item qui avait cette position dans le batch envoyé.

2023-10-09 07:12 UTC, JoMessina approved these changes

2023-10-09 07:17 UTC, sebprt approved these changes

2023-10-09 07:57 UTC, gplanchat requested changes

2023-10-09 07:57 UTC, gplanchat commented on src/Client/MultiStatusResponseException.php
> +        parent::__construct($message);
On perd les arguments `$previous` et `$code`

2023-10-10 13:16 UTC, JoMessina approved these changes

2023-10-12 07:44 UTC, merged